### ISSUE TITLE
Fix ListProperty imports

### ISSUE THREAD

**Issue by tlugger** [nio-blocks/stock#26]
The `ListProperty` in the stock_block is not coming from the correct import. From what I can tell, the import line should be from `nio.properties.list` rather than `nio.properties.List`. `StringType` will also need to be imported with `nio.types.string` and added to the type for the queries `ListProperty`.

**Comment by mattdodge** [comment]
@tyoungNIO sounds like you were working on this today, maybe your code will fix this?
